#!/usr/bin/env bash
#
# Checks if Node.js and NPM are installed, retrieves the installed version numbers,
# and fetches the version numbers for the latest releases.
#
# Author:
#   Larry Gordon
#
# Usage:
#   $ curl -sSL https://raw.githubusercontent.com/psyrendust/nodejscheck/master/nodejscheck | bash
#
# License:
#   The MIT License (MIT) <http://psyrendust.mit-license.org/2014/license.html>
# ------------------------------------------------------------------------------
printf '\n\033[0;33m%s\033[0m\n' "Checking your system for Node.js and NPM..."

node_version_latest="v$(curl -sSL http://nodejs.org/ | grep "Current Version:" | sed 's/[^0-9.]*//g')"
npm_version_latest="$(curl -sSL https://registry.npmjs.org/npm/latest | cut -d',' -f1 | grep "version" | sed 's/[^0-9.]*//g')"

if test $(which node); then
  node_version_current="$(node --version)"
else
  node_version_current="MISSING"
fi

if test $(which npm); then
  npm_version_current="$(npm --version)"
else
  npm_version_current="MISSING"
fi

if [[ "$node_version_latest" != "$node_version_current" ]]; then
  node_update="YES"
else
  node_update="NO"
fi
if [[ "$npm_version_latest" != "$npm_version_current" ]]; then
  npm_update="YES"
else
  npm_update="NO"
fi

printf '\n'
printf '\033[1;37m%9s:\033[0m \033[1;37m%12s\033[0m \033[1;37m%12s\033[0m \033[1;37m%8s\033[0m\n' "Releases" "Latest" "Installed" "Update"
printf '\033[1;37m%s\033[0m\n' "----------------------------------------------"
printf '\033[1;37m%9s:\033[0m \033[0;32m%12s\033[0m \033[0;36m%12s\033[0m \033[0;33m%8s\033[0m\n' "Node" "$node_version_latest" "$node_version_current" "$node_update"
printf '\033[1;37m%9s:\033[0m \033[0;32m%12s\033[0m \033[0;36m%12s\033[0m \033[0;33m%8s\033[0m\n' "NPM"  "$npm_version_latest"  "$npm_version_current" "$npm_update"
